# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
lang                     : "en-US"
title                    : "Yixuan Xu"
title_separator          : "-"
name                     : &name "Yixuan Xu (徐毅轩)"
description              : &description "Homepage"
url                      : https://yxx6.github.io
baseurl                  : ""
repository               : "yxx6/yxx6.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Yixuan Xu (徐毅轩)"
  pronouns         :
  bio              : "Undergraduate at USTC"
  location         : "China"
  employer         :
  uri              :
  email            : "yxxu2005@gmail.com"
  wechat           : "his_WeixinID"

  arxiv            :
  googlescholar    :
  impactstory      :
  orcid            :
  semantic         :
  pubmed           :
  researchgate     :
  scopus           :

  bitbucket        :
  codepen          :
  dribbble         :
  github           : "yxx6"
  kaggle           :
  stackoverflow    :

  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : true
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
social:
  type                   :
  name                   :
  links:

# Analytics
analytics:
  provider               :  "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
  - markdown_generator
  - talkmap
  - talkmap.ipynb
  - talkmap.py
  - _pages/archive-layout-with-content.md
  - _pages/category-archive.html
  - _pages/collection-archive.html
  - _pages/cv.md
  - _pages/markdown.md
  - _pages/non-menu-page.md
  - _pages/page-archive.html
  - _pages/portfolio.html
  - _pages/tag-archive.html
  - _pages/talkmap.html
  - _pages/talks.html
  - _pages/teaching.html
  - _pages/terms.md
  - _pages/year-archive.html
  - _drafts
  - _talks
  - _teaching
  - _portfolio
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  teaching:
    output: false
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: false
    permalink: /:collection/:path/
  talks:
    output: false
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  - scope:
      path: ""
    values:
      sitemap: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
